### ISSUE TITLE
请问怎么后台运行啊

### ISSUE THREAD

**Issue by Zikinn** [juzeon/dd-signal#2]

**Comment by juzeon** [comment]
可以使用pm2后台运行哦。我已经为此更新了README，去看看吧。
Linux上也可以使用screen工具。

**Comment by Zikinn** [comment]
> 可以使用pm2后台运行哦。我已经为此更新了README，去看看吧。
> Linux上也可以使用screen工具。

好的，感谢

**Comment by Zikinn** [comment]
> 可以使用pm2后台运行哦。我已经为此更新了README，去看看吧。
> Linux上也可以使用screen工具。

搞定啦，THX
![image](https://user-images.githubusercontent.com/67361871/109411005-c54db380-79d9-11eb-8fd2-8ce1c6275640.png)
