### ISSUE TITLE
监控失效

### ISSUE THREAD

**Issue by iceJourney** [juzeon/dd-signal#4]
6.19中午起，截止现在（21:37:46）监控列表状态均为未开播，不知道是什么原因
![image](https://user-images.githubusercontent.com/18734597/122644209-ad479e80-d146-11eb-8b5a-eee73e273900.png)

**Comment by juzeon** [comment]
服务器出现问题，现已恢复。
演示服务器可能出现临时问题，您可以考虑按照说明文档自行搭建。

**Comment by iceJourney** [comment]
感谢修复
职业不是玩代码的，实在不懂怎么部署，只有借您的演示服务器日常用
